services:
  - type: web
    name: medrep-backend
    env: python
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python data_loader.py
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini

